name: MobGUI
main: me.cosmicarts.MobGUI.Main
version: 1.0
description: Spawns MobGUI Sheep or displays MobGUI Information.

commands:
  mg:
    description: Spawns MobGUI Sheep or displays MobGUI Information. <about/spawn>
